### ISSUE TITLE
the class Room already existis

### ISSUE THREAD

**Issue by samusam** [TheSniperFan/unityserializer-ng#13]
My error is CS0101: The namespace `global::' already contains a definition for `Room'
the other Room file is the photon unity network plugin and I  can't delet because this is in use in the program.

**Comment by lobby417** [comment]
Odd. I'm using Photon fine with my project and there's no issue.

**Comment by TheSniperFan** [comment]
I don't use Photon, so I couldn't know, but if @lobby417 is right, you must have written it yourself. Place it in a namespace.
Generally speaking, all your code should be in namespaces.

In case you wonder why us-ng doesn't use them:
IIRC Unity had problems with namespaces in the past. Given that the original asset is quite old, chances are that the developer didn't use them for this exact reason.
However, it was a huge mistake to name a class as generic as "Room".

I tried moving everything into namespaces by hand, but it was a huge PITA. I'll probably grab ReSharper in the future, but right now I don't want to spend 150€ on it.

**Comment by samusam** [comment]
so what can i do?
In word easy(I'am italian and speak little english)

**Comment by samusam** [comment]
Place it in a namespace?  what does it mean? Can you insert the example?

**Comment by samusam** [comment]
now i add namespace Comodo in file room but another error i have :)
error CS1671: A namespace declaration cannot have modifiers or attributes

**Comment by TheSniperFan** [comment]
This should help:
[MSDN Namespaces](https://msdn.microsoft.com/it-it/library/z2kcy19k.aspx)

Basically if you have:
```C#
public class Room { ... }
```
You turn it into:
```C#
namespace Comodo {
    public class Room { ... }
}
```
When calling it, you did:
```C#
Room.Something();
```
And now do:
```C#
Comodo.Room.Something();
```

**Comment by samusam** [comment]
yes i understand, but i don't wrote unityserializer-ng. I should change it in the dipendece of Room. Now the error are 7 in XmlSupport.cs and 1 in LevelSerializer.cs.
they are the some erro that i has when i changed the name of Room

**Comment by TheSniperFan** [comment]
**DON'T** change the Room.cs of unityserializer-ng.
There must be another Room.cs in your project.

Chances are that it will be much easier.

**Comment by samusam** [comment]
i hope that the error that i see, would is limitated. now i have this error
 error CS0104: `Hashtable' is an ambiguous reference between `ExitGames.Client.Photon.Hashtable' and `System.Collections.Hashtable'
in photon's room

**Comment by samusam** [comment]
I solved. I cancelled the photon network! :) Now i try this system

**Comment by samusam** [comment]
I hope that the new release of this system does not entry in conflict of the class name.
Photon doesn't use in my project.

**Comment by samusam** [comment]
tnks you all

**Comment by TheSniperFan** [comment]
Weird...
I just downloaded Photon and it worked fine with us-ng.

Anyway, glad you've got everything worked out. :smile:
