### ISSUE TITLE
save game manager, pause menu

### ISSUE THREAD

**Issue by samusam** [TheSniperFan/unityserializer-ng#14]
Hi,
i see that the pause menu have the variable: paused menu, such as a gui texture. Now this don't uses it. How make I at insert a gui texture? the gui texture don't is in use from unity 4.6.
Greetings Samuele

**Comment by samusam** [comment]
Or create a gui texture?

**Comment by lobby417** [comment]
They're called sprites in Unity 4.6 and above.

**Comment by samusam** [comment]
Now i created a sprite but doesn't it go in pause gui. What is the procedure for insert a sprite in variable gui texture?

**Comment by lobby417** [comment]
Hold on, I'll try it on my own system.

**Comment by samusam** [comment]
ok

**Comment by lobby417** [comment]
As GUITexture is now deprecated, you'll have to create a GameObject with a
GUITexture component, and then use that.

**Comment by samusam** [comment]
ok, tnks

**Comment by TheSniperFan** [comment]
Have a look at the example. It's not the most intuitive way to go about this, but the provided PauseMenu script is nothing but a simple example in the first place.
