### ISSUE TITLE
get name the saved when i click on button save

### ISSUE THREAD

**Issue by samusam** [TheSniperFan/unityserializer-ng#17]
Hi,
i get the file's name when i load the file:
GameObject.FindWithTag("Personaggio").SendMessage("OnGUICarica",sg.Data);
i insert this code in foreach into pause menu. 
But i don't have the name file when i save the game:
if (GUILayout.Button("Salva gioco")) {
            DateTime t = DateTime.Now;
			incrementa++;
			print (incrementa);
			/*if(incrementa >=livello){
				diminuisciScroller = diminuisciScroller +0.2f;
				livello = livello +livello;
			}*/

            LevelSerializer.SaveGame(gameName);
.....
how i can to do?

**Comment by TheSniperFan** [comment]
I have no idea what you're trying to tell me. :-/

**Comment by samusam** [comment]
Ok, np. 
Now i would know why when I save and load the game in play mode all is correct, but if i stop the unity's run and after i run unity i don't have all variable stored. where i wrong?

**Comment by lobby417** [comment]
Sounds like you want the variables to auto-populate when you enter play
mode. You'll have to make a script for that.

**Comment by samusam** [comment]
ok tnks, but where i start for it?

**Comment by lobby417** [comment]
Just use the Start() function and add that as a component to something.
Look at the examples for the code to use.

**Comment by samusam** [comment]
So, i create a component, in start function i set the variable that are activate if i load a particular a game saved

**Comment by lobby417** [comment]
Yes. When you save the game, the variables are stored.

**Comment by samusam** [comment]
can you send me the link with the example?

**Comment by samusam** [comment]
i don't know the process of serializer

**Comment by lobby417** [comment]
Is your game object set to store variables in the editor?

**Comment by samusam** [comment]
i don't know. I use unitySerializer as it is in video tutorial

**Comment by lobby417** [comment]
That's your problem. You're using an old tutorial. I'll make one later.

**Comment by samusam** [comment]
ok, tnks. how many time for it?

**Comment by lobby417** [comment]
One moment.

**Comment by lobby417** [comment]
This should help. I've written a tutorial on using unityserializer-ng. Read all of it, and you shouldn't have any problem.

https://github.com/lobby417/unityserializer-ng/blob/master/TUTORIAL.md

**Comment by samusam** [comment]
ok tnks

**Comment by TheSniperFan** [comment]
Thanks @lobby417 
:+1:
