### ISSUE TITLE
'Obsolete' notification from Unity

### ISSUE THREAD

**Issue by PentagramPro** [TheSniperFan/unityserializer-ng#20]
I just cloned US-NG and dragged its folder to my current project (according to new Quickstart guide). Unity has imported scripts and notified me about obsolete code. It suggested conversion. Conversion went well, however.
This is note a bug, but I suppose you have to update code in repository.

**Comment by lobby417** [comment]
What? Which commit did you clone? Is the project empty? US-NG was already
converted to Unity 5 months ago.

**Comment by PentagramPro** [comment]
Reproduced this issue again as following:
1. Cloned latest commit with SmartGit. 
2. Created new project in Unity 5.1.1f1
3. Dragged US-NG folder into this project
4. Received 'Obsolete' notification
5. Declined autoconversion
Now I can see the reason in log:
Assets/unityserializer-ng/Assets/Plugins/Editor/OpenUnityTools/unityserializer-ng/ShaderDB/ShaderDBGenerator.cs(87,37): error CS0619: `UnityEngine.Resources.LoadAssetAtPath<UnityEngine.Shader>(string)' is obsolete: `Use AssetDatabase.LoadAssetAtPath<T>() instead (UnityUpgradable) -> * [UnityEditor] UnityEditor.AssetDatabase.LoadAssetAtPath<T>([mscorlib] System.String)'

**Comment by lobby417** [comment]
Interesting. Thanks for informing me. Hopefully, the actual project creator
will see this and fix it. If not, I will.

**Comment by TheSniperFan** [comment]
Was an Unity update released recently?

Anyway, with usng you'll get a few warnings about outdated/obsolete code (undo-redo code for example).
My plan was to not update the code if it still works.

Since this is part of the ShaderDBGenerator class (which I wrote myself not too long ago), I'll have a look anyway.

**Comment by TheSniperFan** [comment]
Fixed in 2f9d79d15e7a52e75ec804824d1b6410740a4c2c
