### ISSUE TITLE
UI items become enabled (bug or not?)

### ISSUE THREAD

**Issue by PentagramPro** [TheSniperFan/unityserializer-ng#21]
I'm integrating US-NG into my game and i've run into the following problem. Scene contains some UI panels which are disabled by default. They represent different dialog windows and I don't need their state to be stored. I didn't mark them as storeable because I know that US-NG should leave them 'as is' after loading the scene (disabled should remain disabled).
The problem is that they all suddenly become enabled and create a big mess on the screen. Is this intended? How can I workaround it? I'll try to look in the sources but they are a bit complicated...

**Comment by lobby417** [comment]
I'm not too sure. What you may need to do is make a script that gets your
canvases and disables them. Maybe use an array so you can pass as many
gameobjects to be disabled automatically.

**Comment by TheSniperFan** [comment]
I'll look into it today.

**Comment by TheSniperFan** [comment]
Okay, it seems like I cannot reproduce this issue. When a GameObject doesn't contain the `StoreInformation` component, it's ignored. **Completely.**

It must be something else that activates them. Try creating a new, empty project, import the latest usng and reproduce it with a simple setup.

**Comment by PentagramPro** [comment]
I`ve investigated this more closely. In new project I`ve created test objects like this:
 * GameObject
   * Canvas (disabled)
     * Panel
I also created another canvas at top level with 'Save' and 'Load' buttons. At this point everything works fine. When I save game and load it again, canvas remains disabled. However, if I attach StoreInformation component to GameObject, US-NG enables Canvas at loading. In fact it enables all child objects of object that has StoreInformation attached. Is this intended?

**Comment by PentagramPro** [comment]
I've found something interesting. Look at this function from LevelLoader.cs, line 86:
private static void SetActive(GameObject go, bool activate)
```c#
    private static void SetActive(GameObject go, bool activate)
    {
        go.SetActive(activate);
        foreach (var c in go.transform.Cast<Transform>())
        {
            if (c.GetComponent<StoreInformation>() == null)
            {
                SetActive(c.gameObject, activate);
            }
        }
    }
```
It activates object 'go' and all its children that do not have StoreInformation component. But why should it do that? Objects without StoreInformation on them are supposed to remain unchanged and objects with StoreInformation can decide what to do by themselves.

**Comment by TheSniperFan** [comment]
Hmm. I am not entirely sure (and sadly don't have the time to check right
now), but if I recall correctly, the function that was used in the old
Unity Serializer was deprecated and I had to update it.
I'll try tomorrow. If the old function behaves differently, we know of for
certain that this is the problem.

**Comment by TheSniperFan** [comment]
Okay, the old Serializer does this too. I'll have to see what happens here exactly.

**Comment by PentagramPro** [comment]
For my game, I commented it out yet:
```C#
private static void SetActive(GameObject go, bool activate)
    {
        go.SetActive(activate);
        /*foreach (var c in go.transform.Cast<Transform>())
        {
            if (c.GetComponent<StoreInformation>() == null)
            {
                SetActive(c.gameObject, activate);
            }
        }*/
    }
```
Dirty and temporary solution =) But savegames do work for now!

**Comment by TheSniperFan** [comment]
You've gotta be kidding me...

```
if (c.GetComponent<StoreInformation>() == null){
    SetActive(c.gameObject, activate);
}
```

`== null`

It probably has to read `!= null`. It's now setting the state of every component that does __NOT__ have a `StoreInformation` component.

You can try it out yourself and see if it fixes the problem, then report back. I'll do testing myself later.

**Comment by TheSniperFan** [comment]
@PentagramPro :

See if my newest update fixes it.

**Comment by PentagramPro** [comment]
I`ve applied latest changes from repository to my project. If all goes well, I`ll report here in time.
