### ISSUE TITLE
Re-establish links to GameObjects/MonoBehaviours

### ISSUE THREAD

**Issue by Pikl** [TheSniperFan/unityserializer-ng#22]
Hi there dude, first of all, you're awesome.
I found the original serializer recently and was saddened to learn that it doesn't support unity 5 and was just looking into updating it for my project when i stumbled across this wonderful repository. So, thanks!

Anyway, I tried to test it on my StateObjects - a GameObject-ish class that's built to run state machines. Now, within the classes for the states (behaviour) there is a StateObject reference, so that the states can access the GameObject it's running on. 

This reference gets removed when loading a saved game and I'm unable to add it back in when the objects are reconstructed (parameterless constructor) because of how I've built my state machine - it allows states to be stacked up to perform sequences of actions and the States can not get their StateObject reference until they get initialised. 
There are several other reasons why I'm unable to get this reference out of nowhere, I'm sure you understand.

Making the State class inherit from MonoBehaviour would fix this problem as I could store the States in a child object of the StateObject, and have the States as components, then use something like transform.parent.root to always have a reference to the StateObject. 
But this is not really an option for me as it'd completely change the way my framework & game is structured.

I'm not quite sure why I'm posting an issue about this, as it seems to be my problem, not yours.
But any insight you've got would be great - I may be missing something glaringly obvious, as I'm at a loss as to how to proceed and I would really like to use the serializer.

**Comment by TheSniperFan** [comment]
I'm trying to wrap my head around where the problem could lie. For me it's always a bit hard to understand a programming related problem, when there's no code for me to actually look at.
From my perspective, your `StateObject` class and your entire game are a blackbox I merely heard about. My hands are somewhat tied due to this.

Let's get the obvious out of the way first:
How have you tried to store those references? Using the `[SerializeThis]` annotation, I assume.
Is this correct?

**Comment by Pikl** [comment]
I had not tried that!

Unfortunately that doesn't seem to change anything that I can see.
I still get the same NullReferenceException from my objects (player and enemies).
I've tried various different combinations of several annotations, such as [SerializeAll] on the class, [SerializeField], [System.Serializable], and nothing seems to change. 
I may be doing this in entirely the wrong place.
I must admit I'm not too familiar with serialization - I should probably fix that.

I've pasted stripped down versions of my State and StateObject classes, hoping to give you a bit of context.
```C#
public class State {
	[SerializeThis]
	internal StateObject so;
	internal float lifetime, originalLifetime;

	public State() { }

	public State(float lifetime) {
		this.lifetime = lifetime;
		originalLifetime = lifetime;
	}

	//This is where I 'initialize' the state, when a state switch happens, 
	//i.e. idle state to running state.
	internal virtual void Enter(StateObject so) {
		this.so = so;
	}

	internal virtual State Update() {
		if(originalLifetime > 0 && lifetime -= Time.deltaTime == 0)
			so.RevertToPreviousState();//NullReferenceException for so
	}

	//I do a lot of cloning within my StateSequences/NestedStateSequences.
	//Could this be causing problems?
	public object Clone() {
		return new MemberwiseClone();
	}
}

public class StateObject : MonoBehaviour {
    public State CurrentState {
        get {
            return state.Peek().Peek();
        }
    }
    //StateHistory is a class that contains a nested stack of states,
    //States are remembered up to a point - the stack is open,
    //letting the bottom items fall off when capacity is reached.
    StateHistory state;

    void Update() {
        CurrentState.Update();
    }
}
```

**Comment by TheSniperFan** [comment]
Hmmm. Now that I think about it, I need to look whether classes that aren't derived from `MonoBehaviour` are supported at all.
In case they are not, you'll need to use the implement it yourself. The good thing (for you) is that it can be integrated with usng quite easily and that basic serialization is rather straightforward.

If this turns out to be the case, I'll lend you a hand and guide you towards the right direction. It's really not all that complicated.

**Comment by TheSniperFan** [comment]
It seems to work for me. [Here](https://drive.google.com/file/d/0B5AHtBX-WDUFaDJJRUg4UUNWcnM/view?usp=sharing) is the test-setup I used. See if it helps you.

The only issue I am having is that the Non-MonoBehaviour instance doesn't seem to be cleared automatically, if it's supposed to become null after loading. This means that you'll have to do that yourself using the `OnDeserialized()` method and some form of field that stores whether it's supposed to be null or not.

**Comment by Pikl** [comment]
I've had a look at the test you did and it seems as if it doesn't replicate how I've got my stuff set up, so I messed around with it and ended up with [this](https://drive.google.com/file/d/0B6i2DqcyB-AfeXBMU2RKOGxNczQ/view?usp=sharing) (It's just the other way around - NonMonBeh has a reference to MonBeh that it's supposed to lose). 
Now this also works perfectly, after saving/loading all of the classes are still in-tact. There must be some other difference.

I may have to give you a more accurate setup of what I'm using. I'll put something together later today.
The Non-MonoBehaviour instances aren't supposed to be cleared, they are to remain as they were.

**Comment by Pikl** [comment]
Okay so I've pulled in a bunch of scripts and made a few basic ones to simulate the kind of structure that I'm using. You can find it [here](https://drive.google.com/file/d/0B6i2DqcyB-AfamFpRG5kcTVVa3c/view?usp=sharing). Somehow, though. It seems to all be working fine.
I've stuck `[SerializeThis]` over a bunch of things and it seems to be saving all of the fields properly. After a bit more deliberation I've managed to fix my project too by having the various fields in the various classes all under `[SerializeThis]`, originally I had not used it in all of the right places.

There is still a `NullReferenceException` that occurs on loading, but I'm assuming this is during deserialization - the serializer waits 2 frames at one point during deserialization so in turn the references to `so` are still `null` during these 2 frames. 
Since this exception only happens once and not continuously, I'm happy to put a null check in-front of it and call it fixed.

**Comment by TheSniperFan** [comment]
I'm happy you've got it all worked out. :+1:
