### ISSUE TITLE
Namespace errors when building

### ISSUE THREAD

**Issue by BIOS-HAZARD** [TheSniperFan/unityserializer-ng#24]
While using unityserializer-ng i keep getting these errors while building my project (project is android):

Assets/OpenUnityTools/unityserializer-ng/StoreMaterials.cs(9, 7): error CS0246: the type or namespace name 'UnityEditor' could not be found. Are you missing a using directive or assembly reference

and 

Assets/OpenUnityTools/unityserializer-ng/StoreMaterials.cs(148, 37): error CS0246: the type or namespace name 'Editor' could not be found. Are you missing a using directive or assembly reference

**Comment by TheSniperFan** [comment]
Do you use the latest version? (Not the one from the forums, but down
loaded from this repository's master branch)

**Comment by BIOS-HAZARD** [comment]
Yes I am quite sure I am

**Comment by TheSniperFan** [comment]
I'm looking into this right now.
This is really, really weird.

**Comment by TheSniperFan** [comment]
Okay, it seems like I *wasn't* able to reproduce it after all. I got the same compiler error but with a different script. The script in question is a temporary testing script only I have. It's not part of the repository and therefore not relevant.
It builds fine here (PC though). Before we see if this is a very unlikely bug that involves Unity behaving differently when targeting Android, we should first verify that you have the latest version.

Your error message says that the error supposedly happens in line 9 of the "StoreMaterials.cs" file. If you check the current version [here](https://github.com/TheSniperFan/unityserializer-ng/blob/master/Assets/Plugins/OpenUnityTools/unityserializer-ng/Serialization/StoreMaterials.cs), you'll notice that there isn't an "using UnityEngine" there at.

* Check whether the file you have is the same
* If no, download the newest version from the master branch directly of GitHub
* If yes, report back

**Comment by BIOS-HAZARD** [comment]
OK, It doesn't seem to be the same. I will re download and see if it works this time
