### ISSUE TITLE
LevelSerializer.LoadNow reads at a System.Void

### ISSUE THREAD

**Issue by Sohala123** [TheSniperFan/unityserializer-ng#26]
First, I assume that this is not a bug, but rather how it defaults. I am sorry if this is the wrong place to be asking about it. 

Anyway, I am trying to get a direct reference to the object that was loaded with LoadNow (so that I can parent it to where it belongs) and I don't see how to do it. I am hoping I just need to use the fourth argument properly, but I don't know where to start with that. I tried looking at the original site, that appears to be down. The provided pdf has the code for LoadNow listed, but yours already does that.

Any help would be appreciated.

**Comment by TheSniperFan** [comment]
Sorry, but I don't think I quite understand what you're trying to do.
An object x is loaded and afterwards you need to access it directly in
order to parent it to some other object, right?

If so, refer to the "Fixing up after loading" section of the PDF.
OnDeserialized() is meant for that job.

**Comment by Sohala123** [comment]
I have an already loaded object trying to load another object and then parent it to itself, like you say. With OnDeserialized() I think I can attack it from the other end.

Thank you for pointing OnDeserialized() out, it was my own failing for reaching the end of the PDF after finding LoadNow and accepting defeat.
