### ISSUE TITLE
Serializer attempts to destroy transform component

### ISSUE THREAD

**Issue by lgerster** [TheSniperFan/unityserializer-ng#28]
The serializer wants to destroy transform components on loading a level, generating an error message on each attempt. Unfortunately there is no traceback where this is called from the message.
Example:
'Can't destroy Transform component of 'Text'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.'

**Comment by TheSniperFan** [comment]
I'll look into this today.
Does this only happen with certain types?

**Comment by TheSniperFan** [comment]
Can't seem to reproduce this. You'll need to tell me how to reproduce this step by step. And by that I mean starting from an empty project.
