### ISSUE TITLE
I have a problem...

### ISSUE THREAD

**Issue by alguienalex** [TheSniperFan/unityserializer-ng#29]
Very useful! Thank you for this utility

Could you update it once more? the console tells me some warnings, some lines of code are obsolete, sorry for my English...

My Unity Version: 5.3.1
Example:

Assets/Plugins/Editor/OpenUnityTools/unityserializer-ng/UnitySerializerWindow.cs(635,30): warning CS0618: `UnityEditor.Undo.RegisterSceneUndo(string)' is obsolete: `Use DestroyObjectImmediate, RegisterCreatedObjectUndo or RegisterUndo instead.'

Tnxs :)

**Comment by TheSniperFan** [comment]
Ignore the warnings. They don't break builds and I really don't have the time to go about rewriting all the undo-redo code.
You are, of course, free to contribute by fixing them yourself.
